export const BlogActionTypes={
    FETCH_BLOG_ITEM_START:'FETCH_BLOG_ITEM_START',
    FETCH_BLOG_ITEM_SUCCESS:'FETCH_BLOG_ITEM_SUCCESS',
    FETCH_BLOG_ITEM_FAILURE:'FETCH_BLOG_ITEM_FAILURE',
    FETCH_BLOG_DETAIL_START:'FETCH_BLOG_DETAIL_START',
    FETCH_BLOG_DETAIL_SUCCESS:'FETCH_BLOG_DETAIL_SUCCESS',
    FETCH_BLOG_DETAIL_FAILURE:'FETCH_BLOG_DETAIL_FAILURE',

}